#!/bin/sh
function deactivate() {
  if [ -n "$GOENVNAME" ]; then
    unset GOENVNAME
  fi

  if [ -n "$_OLD_GOROOT" ]; then
    export GOROOT="$_OLD_GOROOT"
    unset _OLD_GOROOT
  fi

  if [ -n "$_OLD_PS1" ]; then
    export PS1="$_OLD_PS1"
    unset _OLD_PS1
  fi

  if [ -n "$_OLD_PATH" ]; then
    export PATH="$_OLD_PATH"
    unset _OLD_PATH
  fi

  if [ -n "$_OLD_GOPATH" ]; then
    export GOPATH="$_OLD_GOPATH"
    unset _OLD_GOPATH
  fi

  if [ "$1" != "init" ]; then
    unset -f deactivate
  fi
}

deactivate init

export _OLD_PATH="$PATH"
export _OLD_GOPATH="$GOPATH"
export _OLD_GOROOT="$GOROOT"
export _OLD_PS1="$PS1"
export GOENVNAME="goslides"
export PS1="(go:goslides) $_OLD_PS1"
export GOPATH=/Users/daigoikeda/github/goslides:/Users/daigoikeda/go
export PATH="$GAEGO":"$GOPATH/bin":"$GOROOT/bin":$PATH
export GOROOT=/Users/daigoikeda/google_appengine_go_1.9.6/goroot
