runtime: go111
service: goslides

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /static
  static_dir: static

- url: /.*
  script: auto

nobuild_files: ^(201[0-9]/)
