apiVersion: v1
kind: Pod
metadata:
  name: container-vm-test
spec:
  containers:
    - name: container-vm-test
      image: us.gcr.io/gcpug-containervm/containervm-test-goapp
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
          hostPort: 80

