#cloud-config

write_files:
- path: /etc/systemd/system/testapp.service
  permissions: 0644
  owner: root
  content: |
    [Unit]
    Description=GCPUG Shonan container-vm test app

    [Service]
    ExecStart=docker run -t -p 80:8080 hogedigo/gcpug-containervm-handson

runcmd:
- systemctl daemon-reload
- systemctl start testapp.service

